import { Router } from "express";

import InstituteRouter from "./Routers/InstituteRouter.js";
import BranchRouter from "./Routers/BranchRouter.js";
import AcademicYearRouter from "./Routers/AcademicYearRouter.js";
import HolidayRouter from "./Routers/HolidayRouter.js";
import TimetableRuleRouter from "./Routers/TimetableRuleRouter.js";
import RoleRouter from "./Routers/RoleRouter.js";
import StaffRouter from "./Routers/StaffRouter.js";
import AccessControlRouter from "./Routers/AccessControlRouter.js";
import ClassRouter from "./Routers/ClassRouter.js";
import SubjectRouter from "./Routers/SubjectRouter.js";
import CourseRouter from "./Routers/CourseRouter.js";
import TeacherMappingRouter from "./Routers/TeacherMappingRouter.js";
import TeacherRouter from "./Routers/TeacherRouter.js";
import StudentRouter from "./Routers/StudentRouter.js";
import ParentRouter from "./Routers/ParentRouter.js";
import DepartmentRouter from "./Routers/DepartmentRouter.js";
import FeeStructureRouter from "./Routers/FeeStructureRouter.js";
import FeePolicyRouter from "./Routers/FeePolicyRouter.js";
import PayrollRuleRouter from "./Routers/PayrollRuleRouter.js";
import ExpenseCategoryRouter from "./Routers/ExpenseCategoryRouter.js";
import TaxRouter from "./Routers/TaxRouter.js";
import UploadRouter from "./Routers/UploadRouter.js";
import NoticeRouter from "./Routers/NoticeRouter.js";
import AnnouncementRouter from "./Routers/AnnouncementRouter.js";
import AdmissionRuleRouter from "./Routers/AdmissionRuleRouter.js";
import TransportRouteRouter from "./Routers/TransportRouteRouter.js";
import TransportConfigRouter from "./Routers/TransportConfigRouter.js";
import HostelConfigRouter from "./Routers/HostelConfigRouter.js";
import AssetCategoryRouter from "./Routers/AssetCategoryRouter.js";
import AssetRuleRouter from "./Routers/AssetRuleRouter.js";
import SupportRuleRouter from "./Routers/SupportRuleRouter.js";
import DocumentRuleRouter from "./Routers/DocumentRuleRouter.js";
import ExamPolicyRouter from "./Routers/ExamPolicyRouter.js";
// import ChecklistRouter from "./Routers/ChecklistRouter.js";

const router = Router();

router.use("/api/v1/institute", InstituteRouter);
router.use("/api/v1/branch", BranchRouter);
router.use("/api/v1/academic-year", AcademicYearRouter);
router.use("/api/v1/holiday", HolidayRouter);
router.use("/api/v1/timetable-rule", TimetableRuleRouter);
router.use("/api/v1/role", RoleRouter);
router.use("/api/v1/staff", StaffRouter);
router.use("/api/v1/access-control", AccessControlRouter);
router.use("/api/v1/class", ClassRouter);
router.use("/api/v1/subject", SubjectRouter);
router.use("/api/v1/course", CourseRouter);
router.use("/api/v1/teacher-mapping", TeacherMappingRouter);
router.use("/api/v1/teacher", TeacherRouter);
router.use("/api/v1/student", StudentRouter);
router.use("/api/v1/parent", ParentRouter);
router.use("/api/v1/department", DepartmentRouter);
router.use("/api/v1/fee-structure", FeeStructureRouter);
router.use("/api/v1/fee-policy", FeePolicyRouter);
router.use("/api/v1/payroll-rule", PayrollRuleRouter);
router.use("/api/v1/expense-category", ExpenseCategoryRouter);
router.use("/api/v1/tax", TaxRouter);
router.use("/api/v1/upload", UploadRouter);
router.use("/api/v1/notice", NoticeRouter);
router.use("/api/v1/announcement", AnnouncementRouter);
router.use("/api/v1/admission-rule", AdmissionRuleRouter);
router.use("/api/v1/transport-route", TransportRouteRouter);
router.use("/api/v1/transport-config", TransportConfigRouter);
router.use("/api/v1/hostel-config", HostelConfigRouter);
router.use("/api/v1/asset-category", AssetCategoryRouter);
router.use("/api/v1/asset-rule", AssetRuleRouter);
router.use("/api/v1/support-rule", SupportRuleRouter);
router.use("/api/v1/document-rule", DocumentRuleRouter);
router.use("/api/v1/exam-policy", ExamPolicyRouter);
// router.use("/api/v1/checklist", ChecklistRouter);

export default router;
