
import React from 'react';
import { GraduationCap, School, Calendar } from 'lucide-react';

const Step3_Academic = ({ data, onChange }) => {

    const handleChange = (field, value) => {
        onChange({ ...data, [field]: value });
    };

    return (
        <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-500">

            {/* Header */}
            <div>
                <h3 className="text-lg font-bold text-gray-800 flex items-center gap-2">
                    <GraduationCap className="text-indigo-600" /> Academic Enrollment
                </h3>
                <p className="text-sm text-gray-500">Assign class, section, and record admission details.</p>
            </div>

            {/* Admission Info */}
            <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm grid grid-cols-1 md:grid-cols-2 gap-6">
                <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Admission Number</label>
                    <input
                        type="text"
                        value={data.admissionNo || 'ADM-2024-XXXX'}
                        readOnly
                        className="w-full text-sm border border-gray-200 bg-gray-50 text-gray-500 rounded-lg px-3 py-2 outline-none font-mono cursor-not-allowed"
                    />
                    <p className="text-[10px] text-gray-400 mt-1">Auto-generated by system sequence.</p>
                </div>
                <div>
                    <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Admission Date <span className="text-red-500">*</span></label>
                    <input
                        type="date"
                        value={data.admissionDate || new Date().toISOString().split('T')[0]}
                        onChange={(e) => handleChange('admissionDate', e.target.value)}
                        className="w-full text-sm border border-gray-300 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500"
                    />
                </div>
            </div>

            {/* Class Assignment */}
            <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                <h4 className="text-sm font-bold text-gray-800 mb-4 flex items-center gap-2">
                    <School size={16} className="text-gray-400" /> Class Assignment
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Class <span className="text-red-500">*</span></label>
                        <select
                            value={data.class || ''}
                            onChange={(e) => handleChange('class', e.target.value)}
                            className="w-full text-sm border border-gray-300 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500"
                        >
                            <option value="">Select Class</option>
                            <option value="Class 1">Class 1</option>
                            <option value="Class 2">Class 2</option>
                            <option value="Class 5">Class 5</option>
                            <option value="Class 10">Class 10</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Section</label>
                        <select
                            value={data.section || ''}
                            onChange={(e) => handleChange('section', e.target.value)}
                            className="w-full text-sm border border-gray-300 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500"
                        >
                            <option value="">Select Section</option>
                            <option value="A">A</option>
                            <option value="B">B</option>
                            <option value="C">C</option>
                        </select>
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Roll Number</label>
                        <input
                            type="text"
                            value={data.rollNo || ''}
                            onChange={(e) => handleChange('rollNo', e.target.value)}
                            placeholder="Auto or Manual"
                            className="w-full text-sm border border-gray-300 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500"
                        />
                    </div>
                </div>
            </div>

            {/* Previous School */}
            <div className="bg-white p-6 rounded-xl border border-gray-200 shadow-sm">
                <h4 className="text-sm font-bold text-gray-800 mb-4 flex items-center gap-2">
                    <Calendar size={16} className="text-gray-400" /> Previous History
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Previous School Name</label>
                        <input
                            type="text"
                            value={data.prevSchool || ''}
                            onChange={(e) => handleChange('prevSchool', e.target.value)}
                            className="w-full text-sm border border-gray-300 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500"
                        />
                    </div>
                    <div>
                        <label className="block text-xs font-bold text-gray-500 uppercase mb-1">Last Class Passed</label>
                        <input
                            type="text"
                            value={data.lastClass || ''}
                            onChange={(e) => handleChange('lastClass', e.target.value)}
                            className="w-full text-sm border border-gray-300 rounded-lg px-3 py-2 outline-none focus:ring-2 focus:ring-indigo-500"
                        />
                    </div>
                </div>
            </div>

        </div>
    );
};

export default Step3_Academic;
